build:
  maxIssues: 3
  weights:
    ForbiddenComment: 0
    MatchingDeclarationName: 1
    ReturnCount: 0
    TooGenericExceptionCaught: 0
    TooGenericExceptionThrown: 1

style:
  MagicNumber:
    active: false

console-reports:
  active: true
  # exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'FileBasedFindingsReport'
  #  - 'BuildFailureReport'

processors:
  active: true
  # exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

naming:
  active: true
  variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'
  constantPattern: '^([A-Z_]*|serialVersionUID)$'
  methodPattern: '^[a-z$][a-zA-Z$0-9]*$'
  classPattern: '[A-Za-z$][a-zA-Z_.$]*'
  enumEntryPattern: '^[A-Z$][a-zA-Z_$]*$'
  packagePattern: '[a-zA-Z_$]*'
