name: Android CI

on:
  push:
    branches:
      - master
      - releases/**
      - develop
      - feature/**

jobs:
  test:
    runs-on: macos-latest # To use emulator
    timeout-minutes: 30
    strategy:
      matrix:
        # Currently, no API 30 virtual image
        api-level: [21, 23, 26, 29]
      fail-fast: false
    steps:
    # チェックアウト
    - uses: actions/checkout@v2
      with:
         ref: ${{ github.ref }}

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    # ビルド
    - name: Build with Gradle
      run: ./gradlew build

    # テスト
    - name: Test with Gradle
      run: ./gradlew test --stacktrace

  lint:
    runs-on: ubuntu-latest
    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # 静的解析
    - name: Run Inspection
      run: ./gradlew lint

  detekt:
    runs-on: ubuntu-latest
    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # 静的解析
    - name: Lint with detekt
      run: ./gradlew detekt